In [112]:
from os import listdir
from os.path import isfile, join
import pandas as pd

In [113]:
caminho = "datasets\isolamento\ES"
saida = "datasets\isolamento"

arqs = [ join(caminho, f) for f in listdir(caminho) if isfile(join(caminho, f))]
#print(arqs)
ls = []
for arq in arqs:
    df = pd.read_csv(arq, index_col=None, header=0, encoding="utf-8")
    ls.append(df)
    
dadosES = pd.concat(ls, ignore_index=True, axis=0)   
dadosES

         nm_estado  cd_geouf     indice         dia
0   ESPÍRITO SANTO        32  43.439981  28/07/2021
1   ESPÍRITO SANTO        32  43.383773  29/07/2021
2   ESPÍRITO SANTO        32  42.651289  30/07/2021
3   ESPÍRITO SANTO        32  45.859558  31/07/2021
4   ESPÍRITO SANTO        32  49.919577  01/08/2021
5   ESPÍRITO SANTO        32  42.917957  02/08/2021
6   ESPÍRITO SANTO        32  42.962119  03/08/2021
7   ESPÍRITO SANTO        32  42.936505  04/08/2021
8   ESPÍRITO SANTO        32  42.936378  05/08/2021
9   ESPÍRITO SANTO        32  42.179921  06/08/2021
10  ESPÍRITO SANTO        32  45.548093  07/08/2021
11  ESPÍRITO SANTO        32  50.413233  08/08/2021
12  ESPÍRITO SANTO        32  42.493476  09/08/2021
13  ESPÍRITO SANTO        32  42.473638  10/08/2021
14  ESPÍRITO SANTO        32  42.578329  11/08/2021
15  ESPÍRITO SANTO        32  41.663274  12/08/2021
16  ESPÍRITO SANTO        32  41.735006  13/08/2021
17  ESPÍRITO SANTO        32  44.646286  14/08/2021
18  ESPÍRITO SANTO        32  49.838219  15/08/2021
19  ESPÍRITO SANTO        32  42.588840  16/08/2021
20  ESPÍRITO SANTO        32  42.878188  17/08/2021
21  ESPÍRITO SANTO        32  42.561919  18/08/2021
22  ESPÍRITO SANTO        32  43.033128  19/08/2021
23  ESPÍRITO SANTO        32  42.461030  20/08/2021
24  ESPÍRITO SANTO        32  44.829784  21/08/2021
25  ESPÍRITO SANTO        32  50.129163  22/08/2021
26  ESPÍRITO SANTO        32  42.345176  23/08/2021
27  ESPÍRITO SANTO        32  42.980240  24/08/2021
28  ESPÍRITO SANTO        32  42.931114  25/08/2021
29  ESPÍRITO SANTO        32  42.925214  26/08/2021
30  ESPÍRITO SANTO        32  42.304646  27/08/2021
31  ESPÍRITO SANTO        32  45.052841  28/08/2021
32  ESPÍRITO SANTO        32  49.926037  29/08/2021
33  ESPÍRITO SANTO        32  42.271926  30/08/2021
34  ESPÍRITO SANTO        32  43.609438  31/08/2021

In [114]:
dadosES.to_csv(join(saida, "ES.csv"), index=False)

In [115]:
caminho = "datasets\isolamento\MUN"
arqs = [ join(caminho, f) for f in listdir(caminho) if isfile(join(caminho, f))]
#print(arqs)
ls = []
for arq in arqs:
    df = pd.read_csv(arq, index_col=None, header=0, encoding="utf-8")
    ls.append(df)
    
dadosMUN = pd.concat(ls, ignore_index=True, axis=0)   
dadosMUN

            dia     indice   geocod  cdufmun                     nome
0    28/07/2021  46.630758  3200607   320060                  ARACRUZ
1    28/07/2021  38.281134  3201209   320120  CACHOEIRO DE ITAPEMIRIM
2    28/07/2021  40.956257  3201308   320130                CARIACICA
3    28/07/2021  35.347719  3201506   320150                 COLATINA
4    28/07/2021  41.426855  3202405   320240                GUARAPARI
..          ...        ...      ...      ...                      ...
415  31/08/2021  42.798685  3204906   320490               SÃO MATEUS
416  31/08/2021  40.103710  3205002   320500                    SERRA
417  31/08/2021  45.368059  3205101   320510                    VIANA
418  31/08/2021  40.968393  3205200   320520               VILA VELHA
419  31/08/2021  41.175905  3205309   320530                  VITÓRIA

[420 rows x 5 columns]

In [116]:
dadosMUN.to_csv(join(saida, "MUN.csv"), index=False)